server:
  port: 8081
  error:
    include-message: always

# Configuración de Spring
spring:
  # Configuración de Flyway
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      - classpath:db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  # Configuración del datasource
  datasource:
    url: jdbc:postgresql://stampy.db.elephantsql.com:5432/rrjkyawb
    username: rrjkyawb
    password: FeoRDLwhhtjrNAfMZmDtYfFCZ_Nrgfei
    driverClassName: org.postgresql.Driver
